[package]
name = "img2obj"
version = "0.1.0"
authors = ["Adam Hupp <adam@hupp.org>"]
edition = "2018"

[lib]
name = "img2obj"
path = "src/lib.rs"


[dependencies]
image = "*"

[[bin]]
name = "img2obj"
path = "src/main.rs"
