[package]
name = "img2obj"
version = "0.1.0"
authors = ["Adam Hupp <adam@hupp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
