[package]
name = "stamp-maker"
version = "0.1.0"
authors = ["Adam Hupp <adam@hupp.org>"]
edition = "2018"

[lib]
name = "stamp_maker"
path = "src/lib.rs"


[dependencies]
image = "0.24.5"
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"

